// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsMLAI-g6wlcF2cDxUDy_9QBH71h27KqQ',
    appId: '1:88385033528:web:a2c938988df9cba9629dcd',
    messagingSenderId: '88385033528',
    projectId: 'homework-tracker-23480230',
    authDomain: 'homework-tracker-23480230.firebaseapp.com',
    storageBucket: 'homework-tracker-23480230.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhPevjpC9pRQtyEv3MwVLBZzp2zm0v7Ig',
    appId: '1:88385033528:android:a1259f54016b1d9c629dcd',
    messagingSenderId: '88385033528',
    projectId: 'homework-tracker-23480230',
    storageBucket: 'homework-tracker-23480230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBchyM0XbhYg6_1f-nhfHCHzXaJewQ9pnI',
    appId: '1:88385033528:ios:b340b17ae0fc7be8629dcd',
    messagingSenderId: '88385033528',
    projectId: 'homework-tracker-23480230',
    storageBucket: 'homework-tracker-23480230.firebasestorage.app',
    iosBundleId: 'com.example.homeworkTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBchyM0XbhYg6_1f-nhfHCHzXaJewQ9pnI',
    appId: '1:88385033528:ios:b340b17ae0fc7be8629dcd',
    messagingSenderId: '88385033528',
    projectId: 'homework-tracker-23480230',
    storageBucket: 'homework-tracker-23480230.firebasestorage.app',
    iosBundleId: 'com.example.homeworkTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsMLAI-g6wlcF2cDxUDy_9QBH71h27KqQ',
    appId: '1:88385033528:web:75e8f5f86e4720f0629dcd',
    messagingSenderId: '88385033528',
    projectId: 'homework-tracker-23480230',
    authDomain: 'homework-tracker-23480230.firebaseapp.com',
    storageBucket: 'homework-tracker-23480230.firebasestorage.app',
  );
}
